# Generated by Django 3.1.5 on 2021-01-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('drinks', models.BooleanField(help_text='Este convidado irá beber?')),
            ],
            options={
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('drinks', models.BooleanField(help_text='Este funcionário irá beber?')),
                ('guests', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coreapi.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Barbeque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organized_by', models.CharField(blank=True, max_length=70)),
                ('participants', models.ManyToManyField(to='coreapi.Employee')),
            ],
        ),
    ]
