# Generated by Django 3.1.5 on 2021-01-25 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_auto_20210121_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeque',
            name='_date',
            field=models.DateField(blank='true', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
